-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 12:06:24 2017
-- Model: jwow    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jwow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

CREATE TABLE IF NOT EXISTS `item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idWoW` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `nameEN` VARCHAR(255) NULL DEFAULT NULL,
  `quality` VARCHAR(45) NULL DEFAULT NULL,
  `icon` LONGBLOB NULL DEFAULT NULL,
  `sourceId` VARCHAR(255) NULL DEFAULT NULL,
  `sourceType` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spell` ;

CREATE TABLE IF NOT EXISTS `spell` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idWoW` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `nameEN` VARCHAR(255) NULL DEFAULT NULL,
  `icon` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itemhasspell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itemhasspell` ;

CREATE TABLE IF NOT EXISTS `itemhasspell` (
  `idItem` INT(11) NOT NULL,
  `idSpell` INT(11) NOT NULL,
  PRIMARY KEY (`idItem`, `idSpell`),
  INDEX `fk_Item_has_Spell_Spell1_idx` (`idSpell` ASC),
  INDEX `fk_Item_has_Spell_Item1_idx` (`idItem` ASC),
  CONSTRAINT `fk_Item_has_Spell_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Spell_Spell1`
    FOREIGN KEY (`idSpell`)
    REFERENCES `spell` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mount` ;

CREATE TABLE IF NOT EXISTS `mount` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idItem` INT(11) NULL DEFAULT NULL,
  `idSpell` INT(11) NULL DEFAULT NULL,
  `idCreature` INT(11) NOT NULL COMMENT 'creatureId in Battle net API',
  `name` VARCHAR(255) NOT NULL,
  `nameEN` VARCHAR(255) NULL DEFAULT NULL,
  `quality` VARCHAR(45) NULL DEFAULT NULL,
  `icon` LONGBLOB NULL DEFAULT NULL,
  `isGround` TINYINT(4) NULL DEFAULT NULL,
  `isFlying` TINYINT(4) NULL DEFAULT NULL,
  `isAquatic` TINYINT(4) NULL DEFAULT NULL,
  `isJumping` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mount_Item_idx` (`idItem` ASC),
  INDEX `fk_Mount_Spell1_idx` (`idSpell` ASC),
  CONSTRAINT `fk_Mount_Item`
    FOREIGN KEY (`idItem`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mount_Spell1`
    FOREIGN KEY (`idSpell`)
    REFERENCES `spell` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passwordResets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passwordResets` ;

CREATE TABLE IF NOT EXISTS `passwordResets` (
  `id` INT NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT NOW(),
  INDEX `password_resets_email_index` (`email` ASC),
  INDEX `password_resets_token_index` (`token` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `hashPassword` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `code` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `rememberToken` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT NOW(),
  `updatedAt` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `link` ;

CREATE TABLE IF NOT EXISTS `link` (
  `idlink` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `description` VARCHAR(2000) NULL,
  `idUser` INT(10) NOT NULL,
  PRIMARY KEY (`idlink`),
  INDEX `fk_link_users1_idx` (`idUser` ASC),
  CONSTRAINT `fk_link_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
