-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 12:58:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wowdump
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idWoW` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `nameEN` VARCHAR(255) NULL DEFAULT NULL,
  `quality` VARCHAR(45) NULL DEFAULT NULL,
  `icon` LONGBLOB NULL DEFAULT NULL,
  `sourceId` VARCHAR(255) NULL DEFAULT NULL,
  `sourceType` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16226
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spell` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idWoW` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `nameEN` VARCHAR(255) NULL DEFAULT NULL,
  `icon` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 65235
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `itemhasspell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itemhasspell` (
  `idItem` INT(11) NOT NULL,
  `idSpell` INT(11) NOT NULL,
  PRIMARY KEY (`idItem`, `idSpell`),
  INDEX `fk_Item_has_Spell_Spell1_idx` (`idSpell` ASC),
  INDEX `fk_Item_has_Spell_Item1_idx` (`idItem` ASC),
  CONSTRAINT `fk_Item_has_Spell_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Spell_Spell1`
    FOREIGN KEY (`idSpell`)
    REFERENCES `spell` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mount` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idItem` INT(11) NULL DEFAULT NULL,
  `idSpell` INT(11) NULL DEFAULT NULL,
  `idCreature` INT(11) NOT NULL COMMENT 'creatureId dans l API battle net',
  `name` VARCHAR(255) NOT NULL,
  `nameEN` VARCHAR(255) NULL DEFAULT NULL,
  `quality` VARCHAR(45) NULL DEFAULT NULL,
  `icon` LONGBLOB NULL DEFAULT NULL,
  `isGround` TINYINT(4) NULL DEFAULT NULL,
  `isFlying` TINYINT(4) NULL DEFAULT NULL,
  `isAquatic` TINYINT(4) NULL DEFAULT NULL,
  `isJumping` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mount_Item_idx` (`idItem` ASC),
  INDEX `fk_Mount_Spell1_idx` (`idSpell` ASC),
  CONSTRAINT `fk_Mount_Item`
    FOREIGN KEY (`idItem`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mount_Spell1`
    FOREIGN KEY (`idSpell`)
    REFERENCES `spell` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 578
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC),
  INDEX `password_resets_token_index` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `code` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Link` (
  `idLink` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `idUser` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idLink`),
  INDEX `fk_Link_users1_idx` (`idUser` ASC),
  CONSTRAINT `fk_Link_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `link` (
  `idlink` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `description` VARCHAR(2000) NULL,
  `idUser` INT(10) NOT NULL,
  PRIMARY KEY (`idlink`),
  INDEX `fk_link_users1_idx` (`idUser` ASC),
  CONSTRAINT `fk_link_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
